"""Initial migration

Revision ID: 8c7e09400e7b
Revises: 
Create Date: 2025-01-25 06:19:16.661338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c7e09400e7b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('convention_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_name', sa.String(), nullable=False),
    sa.Column('venue', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_convention_areas'))
    )
    op.create_table('host_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_host_companies'))
    )
    op.create_table('conventions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('convention_name', sa.String(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('convention_area_id', sa.Integer(), nullable=True),
    sa.Column('host_company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['convention_area_id'], ['convention_areas.id'], name=op.f('fk_conventions_convention_area_id_convention_areas')),
    sa.ForeignKeyConstraint(['host_company_id'], ['host_companies.id'], name=op.f('fk_conventions_host_company_id_host_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conventions'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conventions')
    op.drop_table('host_companies')
    op.drop_table('convention_areas')
    # ### end Alembic commands ###
